# Generated by Django 5.2.7 on 2025-11-07 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст оголошення')),
                ('type', models.CharField(choices=[('info', 'Інформація'), ('warning', 'Попередження'), ('success', 'Успіх'), ('danger', 'Важливе')], default='info', max_length=20, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закріплене')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='announcemen_is_acti_14a85b_idx'), models.Index(fields=['is_pinned', 'created_at'], name='announcemen_is_pinn_84b3ee_idx')],
            },
        ),
    ]
